//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashbookApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpenseID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string VoucherNumber { get; set; }
        public string Reference { get; set; }
        public decimal Amount { get; set; }
    }
}
